### ISSUE TITLE
The webui does not open

### ISSUE THREAD

**Issue by Rubiooo04** [wiserain/docker-flexget#74]
**Version container , version docker**
I am using docker-compose with version 1.25.0 and container version wiserain/flexget:3

**Docker-Compose input**
```
  flexget:
    image: wiserain/flexget:3
    volumes:
      - ./flexget:/config
      - ${STORAGE}/torrents:/downloads
      - ${MEDIA}:/storage
    ports:
      - 5050:5050
    environment:
      - TORRENT_PLUGIN=transmission
      - FG_WEBUI_PASSWD=123456
    restart: unless-stopped
    links:
      - transmission
```
**Description**
When I put my_machine_ip:5050 in my browser, the page does not load

**Steps to reproduce the issue:**
 1. docker-compose up -d
 2. go to my_machine_ip:5050

**Describe the results you received:**
The page does not load says; the page my_machine_ip has refused the connection

![aa](https://user-images.githubusercontent.com/77902247/209876100-ba001e1b-e35d-4a55-9059-b92a68e92113.PNG)
**Config.yml**
```
web_server:
  bind: 0.0.0.0
  port: 5050
  # api: yes
  web_ui: yes

schedules:
  - tasks: '*'
    interval:
      minutes: 1
templates:
  tv:
    series:
      settings:
        tv:
          exact: yes
          propers: 12 hours
          quality: 720p
      tv:
      - I am groot
tasks:
  sort_tv:
    priority: 2
    filesystem:
      path: /downloads/complete
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
    accept_all: yes
    require_field: series_name
    move:
      to: '/storage/'
      rename: '{{ series_name }} - {{ series_id }}'
```
Also if anyone wants to help me.

I think my setup says that flexget has to move the files from the /downloads/complete folder, rename it and move it to /storage/ (have to say downloads and storage are variable or so I think), but flexget doesn't that task

It's my first time with flexget maybe it's a very silly mistake
