### ISSUE TITLE
Flexget not working

### ISSUE THREAD

**Issue by Rubiooo04** [wiserain/docker-flexget#75]
**Issue**
I have_ flexget in docker compose and it doesn't work for me

That is, I have this configuration that downloads files from an rss and renames and moves them. But flexget doesn't do any of that

And in the flexget.log it does not give me any error.

I've tried various configurations but it still doesn't work. I don't know what to do anymore. 

**Docker-Compose**
```
  flexget:
    image: wiserain/flexget:3
    volumes:
      - ${CONFIG}:/config
      - ${STORAGE}/torrents:/downloads
      - ${MEDIA}:/storage
    ports:
      - 5050:5050
    environment:
      - TORRENT_PLUGIN=transmission
      - FG_WEBUI_PASSWD=123456
    restart: unless-stopped
    links:
      - transmission
```
**Config.yml**
```
web_server:
  bind: 0.0.0.0
  port: 5050
  web_ui: yes

schedules:
  - tasks: '*'
    interval:
      minutes: 1
templates:
  transmissionrpc:
    transmission:
      host: localhost
      port: 9091
      username: admin
      password: "123456"
    clean_transmission:
      host: localhost
      port: 9091
      username: admin
      password: "123456"
      transmission_seed_limits: yes
      delete_files: no
      enabled: Yes

  tv:
    thetvdb_lookup: yes
    quality: 720p
    series:
      group:      
        - Criminal Minds
        - Rick and Morty
tasks:
  Drarbg task:
    rss: http://showrss.info/user/229110.rss?magnets=true&namespaces=true&name=null&quality=null&re=null
    priority: 1
    all_series: yes
    template: 
      - tv
      - transmissionrpc
    set:
      path: /downloads/complete

  sort-series:
    metainfo_series: yes
    accept_all: yes
    filesystem:
      path: /downloads/complete
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
    template: tv
    series:
      settings:
        group:
          parse_only: yes
    require_field: series_name
    move: 
      to: '/storage/Series/{{series_name}}'  
      rename: '{{series_name}} - S{{series_season|pad(2)}}E{{series_episode|pad(2)}}'
```
**Other info**

The web_ui does not work either, that is, when I put the ip of my machine followed by :5050 it tells me that the connection has been rejected

**Comment by wiserain** [comment]
No problems with opening webui by

```bash
docker run --rm -it -p 5050:5050 -e FG_WEBUI_PASSWD=complexpassword wiserain/flexget:3 bash
```

**Comment by Rubiooo04** [comment]
> No problems with opening webui by
> 
> ```shell
> docker run --rm -it -p 5050:5050 -e FG_WEBUI_PASSWD=complexpassword wiserain/flexget:3 bash
> ```

Ok thx, I managed to open the webui 

But now when i run a `sort_tv` task it gives me this error:

`failure reason: [Errno 13] Permission denied: '/storage/Series/Criminal Minds`

#### Sort_tv:

```
task:
  sort_tv:
    metainfo_series: yes
    accept_all: yes
    filesystem:
      path: /downloads/complete
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
    require_field: series_name
    move:
      to: '/storage/Series/{{series_name}}'
      rename: '{{series_name}} - S{{series_season|pad(2)}}E{{series_episode|pad>

```

I don't know how to give it permissions because of the little I know about Linux, in theory it should already have permissions


![Permisos](https://user-images.githubusercontent.com/77902247/210267138-bb520cea-4281-41d0-a54a-4d947525143f.PNG)

As you can see that folder is readable and writeable for whatever
